### ISSUE TITLE
Bitbucket Pipeline error "could not find driver"

### ISSUE THREAD

**Issue by emarcus255** [magarrent/laravel-url-shortener#8]
Hi,

First of all great work with the package. I love the simplicity. 

I have installed it on my local host and all worked fine, but when I ran in on a bitbucket pipeline I have got the following error:

`could not find driver (SQL: select * from information_schema.tables where table_schema = forge and table_name = url_shorteners and table_type = 'BASE TABLE')  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:760`

Using PHP 8.1.15 
Any idea how to solve it?

**Comment by magarrent** [comment]
Hi @MarekMaz , thank you mate!

Honestly, I always had problems with Pipelines/Actions and MySQL, same problem as you, the Mysql machine does not connect to the Laravel app, so I'm really sorry but I can't help with this :(

Maybe you could try using postgres or SQLite to run the pipeline if possible.

Let me know if you find out the solution!
